### ISSUE TITLE
return none

### ISSUE THREAD

**Issue by MrAuronTV** [Woodie-07/EarnApp.py#1]
Hello

I want to use this api for auto link my device , its work but after 3 link , i have "None" and script crash

Successfully logged in!
{'status': 'ok'}
{'status': 'ok'}
{'status': 'ok'}
None
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

Any help ?
Thanks

**Comment by Woodie-07** [comment]
Can you send your Python script that you are using to auto link the devices? Make sure you remove your token.

**Comment by MrAuronTV** [comment]
`#!/usr/bin/env python3
from earnapp import earnapp

user = earnapp.User()
loggedIn = user.login("token")

# file contain sdk node
file = open('earnapp.txt', "r")
# read file
lines = file.readlines()
# close the file
file.close()

if loggedIn == True: 
   print("Successfully logged in!")
   for line in lines: #browse file line after line , strip revoce space
       print(user.linkDevice(line.strip()))
else:
   print("Failed to log in")

`

**Comment by Woodie-07** [comment]
Why closed?

**Comment by MrAuronTV** [comment]
its ok , i have add a time.sleep(120) for dont spam website and it works ^^
